name: tests

on:
  push:
  pull_request:
    branches:
      - master

jobs:
  test:
    name: ${{ matrix.ruby }} - ${{ matrix.gemfile }}
    runs-on: ubuntu-latest
    env:
      COVERAGE_RUBY_VERSION: 2.6
      BUNDLE_GEMFILE: gemfiles/${{ matrix.gemfile }}.gemfile
    strategy:
      fail-fast: false
      matrix:
        ruby:
          - 2.6
          - 2.7
          - '3.0' # Due to https://github.com/actions/runner/issues/849, we have to use quotes for '3.0'
          - 3.1
          - 3.2
          - jruby
          - truffleruby
        gemfile:
          - sinatra
          - rails_5.2
          - rails_6.0
          - rails_6.1
        exclude:
          - ruby: 2.6
            gemfile: rails_7.0
          - ruby: 2.7
            gemfile: rails_5.2
          - ruby: '3.0'
            gemfile: rails_5.2
          - ruby: '3.0'
            gemfile: rails_6.0
          - ruby: 3.1
            gemfile: rails_5.2
          - ruby: 3.1
            gemfile: rails_6.0
          - ruby: 3.2
            gemfile: rails_5.2
          - ruby: 3.2
            gemfile: rails_6.0
          - ruby: jruby
            gemfile: rails_5.2
          - ruby: jruby
            gemfile: rails_6.0
          - ruby: truffleruby
            gemfile: rails_5.2
          - ruby: truffleruby
            gemfile: rails_6.0
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Prepare environment
        run: |
          sudo apt-get -y install libsqlite3-dev libxslt1-dev
      - name: Setup ruby ${{ matrix.ruby }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - name: Test
        run: bundle exec rspec

      - name: Publish code coverage
        if: startsWith(env.RUBY_VERSION, env.COVERAGE_RUBY_VERSION)
        uses: paambaati/codeclimate-action@v2.3.0
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          coverageCommand: bundle exec rspec
